My Project: SC_PauseMenu Class Reference
SC_PauseMenu Class Reference
Public Member Functions
void MainMenuButton ()
void PauseMenuButton ()
void OptionsMenuButton ()
void PauseGameToggle ()
void ResumeGame ()
void RestartLevel ()
void SaveBotData ()
void SetBotTankControls ()
void SetPythonBot ()
void SetSelectedObject (GameObject obj)
Public Attributes
GameObject PauseMenu
GameObject OptionsMenu
Toggle tankControlsToggle
Toggle pythonToggle
Member Function Documentation
MainMenuButton()
void SC_PauseMenu.MainMenuButton ()
References LevelManager.LoadLevel(), SaveBotData(), and LevelManager.SetSelectedLevel().
OptionsMenuButton()
void SC_PauseMenu.OptionsMenuButton ()
References OptionsMenu, and PauseMenu.
PauseGameToggle()
void SC_PauseMenu.PauseGameToggle ()
References LevelManager.isPaused, and ResumeGame().
PauseMenuButton()
void SC_PauseMenu.PauseMenuButton ()
References OptionsMenu, and PauseMenu.
RestartLevel()
void SC_PauseMenu.RestartLevel ()
References LevelManager.RestartLevel().
ResumeGame()
void SC_PauseMenu.ResumeGame ()
References SIMbot.EnableCameraOrbit(), OptionsMenu, PauseMenu, and LevelManager.ResumeLevel().
Referenced by PauseGameToggle().
SaveBotData()
void SC_PauseMenu.SaveBotData ()
References SaveManager.SaveSBData(), and SIMbot.SaveSIMbotOptions().
Referenced by MainMenuButton().
SetBotTankControls()
void SC_PauseMenu.SetBotTankControls ()
References SIMbot.SetTankControls(), and tankControlsToggle.
SetPythonBot()
void SC_PauseMenu.SetPythonBot ()
References pythonToggle, and SIMbot.SetPythonBot().
SetSelectedObject()
void SC_PauseMenu.SetSelectedObject (GameObject obj)
Member Data Documentation
OptionsMenu
GameObject SC_PauseMenu.OptionsMenu
Referenced by OptionsMenuButton(), PauseMenuButton(), and ResumeGame().
PauseMenu
GameObject SC_PauseMenu.PauseMenu
Referenced by OptionsMenuButton(), PauseMenuButton(), and ResumeGame().
pythonToggle
Toggle SC_PauseMenu.pythonToggle
Referenced by SetPythonBot().
tankControlsToggle
Toggle SC_PauseMenu.tankControlsToggle
Referenced by SetBotTankControls().
The documentation for this class was generated from the following file:
C:/Users/kiome/Documents/Unity Projects/SIMBoT2021/Assets/Scripts/Menu/SC_PauseMenu.cs