My Project: SaveManager Class Reference
SaveManager Class Reference
Public Member Functions
void SaveSBData ()
Save the data on the SIMbot to a file.
string LoadSBData ()
Load the SIMbot data from a file.
Member Function Documentation
LoadSBData()
string SaveManager.LoadSBData ()
Load the SIMbot data from a file.
Referenced by SIMbot.LoadSIMbotDataFromFile().
SaveSBData()
void SaveManager.SaveSBData ()
Save the data on the SIMbot to a file.
References SIMbot.SBData.
Referenced by SC_PauseMenu.SaveBotData(), SC_MainMenu.SaveSBData(), and SIMbot.SaveSIMbotDataToFile().
The documentation for this class was generated from the following file:
C:/Users/kiome/Documents/Unity Projects/SIMBoT2021/Assets/Scripts/Managers/SaveManager.cs