My Project: SC_MainMenu Class Reference
SC_MainMenu Class Reference
Public Member Functions
void ExitButton ()
void OptionsButton ()
void MainMenuButton ()
void CustomizationButton ()
void LevelSelectButton ()
void PlayButton ()
void UpdateAttachmentNumber ()
void NextAttachment ()
void PreviousAttachment ()
void ToggleLED ()
void SetSelectedLevel (int levelNumber)
void SaveSBData ()
void SetBotTankControls ()
void SetPythonBot ()
void SetSelectedObject (GameObject obj)
Public Attributes
GameObject MainMenu
GameObject OptionsMenu
GameObject CustomizationMenu
GameObject LevelSelectionMenu
Toggle pythonToggle
Toggle tankControlsToggle
Text attachmentNumberText
int currentlySelectedLevel = 1
Member Function Documentation
CustomizationButton()
void SC_MainMenu.CustomizationButton ()
References CustomizationMenu, MainMenu, OptionsMenu, and UpdateAttachmentNumber().
ExitButton()
void SC_MainMenu.ExitButton ()
LevelSelectButton()
void SC_MainMenu.LevelSelectButton ()
References CustomizationMenu, LevelSelectionMenu, MainMenu, and OptionsMenu.
MainMenuButton()
void SC_MainMenu.MainMenuButton ()
References CustomizationMenu, LevelSelectionMenu, MainMenu, and OptionsMenu.
NextAttachment()
void SC_MainMenu.NextAttachment ()
References SIMbot.NextAttachment(), and UpdateAttachmentNumber().
OptionsButton()
void SC_MainMenu.OptionsButton ()
References CustomizationMenu, MainMenu, and OptionsMenu.
PlayButton()
void SC_MainMenu.PlayButton ()
References CustomizationMenu, LevelSelectionMenu, LevelManager.LoadLevel(), MainMenu, and OptionsMenu.
PreviousAttachment()
void SC_MainMenu.PreviousAttachment ()
References SIMbot.PreviousAttachment(), and UpdateAttachmentNumber().
SaveSBData()
void SC_MainMenu.SaveSBData ()
References SaveManager.SaveSBData().
SetBotTankControls()
void SC_MainMenu.SetBotTankControls ()
References SIMbot.SetTankControls(), and tankControlsToggle.
SetPythonBot()
void SC_MainMenu.SetPythonBot ()
References pythonToggle, and SIMbot.SetPythonBot().
SetSelectedLevel()
void SC_MainMenu.SetSelectedLevel (int levelNumber)
References currentlySelectedLevel.
Referenced by LevelButton.SetCurrentlySelectedLevel().
SetSelectedObject()
void SC_MainMenu.SetSelectedObject (GameObject obj)
ToggleLED()
void SC_MainMenu.ToggleLED ()
References SIMbot.ToggleLED().
UpdateAttachmentNumber()
void SC_MainMenu.UpdateAttachmentNumber ()
References SIMbot.attachmentNumber, and attachmentNumberText.
Referenced by CustomizationButton(), NextAttachment(), and PreviousAttachment().
Member Data Documentation
attachmentNumberText
Text SC_MainMenu.attachmentNumberText
Referenced by UpdateAttachmentNumber().
currentlySelectedLevel
int SC_MainMenu.currentlySelectedLevel = 1
Referenced by SetSelectedLevel().
CustomizationMenu
GameObject SC_MainMenu.CustomizationMenu
Referenced by CustomizationButton(), LevelSelectButton(), MainMenuButton(), OptionsButton(), and PlayButton().
LevelSelectionMenu
GameObject SC_MainMenu.LevelSelectionMenu
Referenced by LevelSelectButton(), MainMenuButton(), and PlayButton().
MainMenu
GameObject SC_MainMenu.MainMenu
Referenced by CustomizationButton(), LevelSelectButton(), MainMenuButton(), OptionsButton(), and PlayButton().
OptionsMenu
GameObject SC_MainMenu.OptionsMenu
Referenced by CustomizationButton(), LevelSelectButton(), MainMenuButton(), OptionsButton(), and PlayButton().
pythonToggle
Toggle SC_MainMenu.pythonToggle
Referenced by SetPythonBot().
tankControlsToggle
Toggle SC_MainMenu.tankControlsToggle
Referenced by SetBotTankControls().
The documentation for this class was generated from the following file:
C:/Users/kiome/Documents/Unity Projects/SIMBoT2021/Assets/Scripts/Menu/SC_MainMenu.cs