My Project: LevelManager Class Reference
LevelManager Class Reference
Public Member Functions
void SetSelectedLevel (int levelNumber)
This method changes the point's location to the given coordinates.
int GetSelectedLevel ()
This method returns the selected level.
void LoadLevel (int levelNumber)
This method sets the selected level to the given level number.
void LoadLevel ()
Load a scene with the current level number.
void PauseLevel ()
Pauses the level.
void ResumeLevel ()
Resumes the level.
void RestartLevel ()
Restarts the level.
string GetLevelName ()
Return the current scene's name
bool InMainMenuScene ()
Returns whether or not we are in the main menu scene.
Public Attributes
int selectedLevel = 1
Instance variable selectedLevel represents the currently selected level.
string[] sceneNames
Instance variable sceneNames represents the list of scene names.
bool isPaused
Instance variable isPaused whether the game is paused or not.
Member Function Documentation
GetLevelName()
string LevelManager.GetLevelName ()
Return the current scene's name
Returns
The scene's name.
GetSelectedLevel()
int LevelManager.GetSelectedLevel ()
This method returns the selected level.
Returns
The selected level
References selectedLevel.
InMainMenuScene()
bool LevelManager.InMainMenuScene ()
Returns whether or not we are in the main menu scene.
Returns
True if we're in the main menu scene; otherwise, false.
LoadLevel() [1/2]
void LevelManager.LoadLevel ()
Load a scene with the current level number.
References sceneNames, and selectedLevel.
Referenced by LoadLevel().
LoadLevel() [2/2]
void LevelManager.LoadLevel (int levelNumber)
This method sets the selected level to the given level number.
levelNumber is the new level number.
References LoadLevel(), and SetSelectedLevel().
Referenced by SC_PauseMenu.MainMenuButton(), and SC_MainMenu.PlayButton().
PauseLevel()
void LevelManager.PauseLevel ()
Pauses the level.
References isPaused.
RestartLevel()
void LevelManager.RestartLevel ()
Restarts the level.
Referenced by SC_PauseMenu.RestartLevel().
ResumeLevel()
void LevelManager.ResumeLevel ()
Resumes the level.
References isPaused.
Referenced by SC_PauseMenu.ResumeGame().
SetSelectedLevel()
void LevelManager.SetSelectedLevel (int levelNumber)
This method changes the point's location to the given coordinates.
levelNumber is the new level number.
References selectedLevel.
Referenced by LoadLevel(), SC_PauseMenu.MainMenuButton(), and LevelButton.SetCurrentlySelectedLevel().
Member Data Documentation
isPaused
bool LevelManager.isPaused
Instance variable isPaused whether the game is paused or not.
Referenced by SC_PauseMenu.PauseGameToggle(), PauseLevel(), and ResumeLevel().
sceneNames
string [] LevelManager.sceneNames
Instance variable sceneNames represents the list of scene names.
Referenced by LoadLevel().
selectedLevel
int LevelManager.selectedLevel = 1
Instance variable selectedLevel represents the currently selected level.
Referenced by GetSelectedLevel(), LoadLevel(), and SetSelectedLevel().
The documentation for this class was generated from the following file:
C:/Users/kiome/Documents/Unity Projects/SIMBoT2021/Assets/Scripts/Managers/LevelManager.cs